export const Catalogues = [
    {
        id: '1',
        title: 'Magpie552979.mp3',
        percentage: '95%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'stork',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Никита',
        created: '05/06/2022',
        update: '07/06/2022'
    },
    {
        id: '2',
        title: 'Magpie552979.mp3',
        percentage: '80%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'albatross',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Гена',
        created: '05/06/2022',
        update: '07/06/2022'
    },
    {
        id: '3',
        title: 'Magpie552979.mp3',
        percentage: '80%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'crane',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Стас',
        created: '05/06/2022',
        update: '07/06/2022'
    },
    {
        id: '4',
        title: 'Magpie552979.mp3',
        percentage: '80%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'swan',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Володя',
        created: '05/06/2022',
        update: '07/06/2022'
    },
    {
        id: '5',
        title: 'Magpie552979.mp3',
        percentage: '80%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'penguin',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Игорь',
        created: '05/06/2022',
        update: '07/06/2022'
    },
    {
        id: '6',
        title: 'Magpie552979.mp3',
        percentage: '80%',
        bird_specie: 'Magpie',
        second_specie: 'european magpie',
        latinName: 'Pica pica',
        englishName: 'tomtit',
        belarusianName: 'Saroka',
        validated: 'Yes',
        xeno_canto: 'xeno link',
        annotation: 'annotation',
        audio_quality: 'high',
        photo_quality: 'low',
        spectogram: 'spectrogram.png',
        userName: 'Олег',
        created: '05/06/2022',
        update: '07/06/2022'
    }
]